export const tryandcatch = (fn, req, res) =>{
    try {
        
    } catch (error) {
        
    }
}